### ISSUE TITLE
Add Powershell Support

### ISSUE THREAD

**Issue by ziabytes** [replit/polygott#270]
Can you add Powershell support?

**Comment by lhchavez** [comment]
We are moving away from Polygott (https://github.com/replit/polygott/issues/272) and into [nix](https://blog.replit.com/nix). Powershell [is already supported](https://search.nixos.org/packages?channel=21.05&show=powershell&from=0&size=50&sort=relevance&type=packages&query=powershell) in nix!

Closing this since there is a way to get powershell in replit.
